export const projects = [
  {
    id: 1,
    title: "Cinemaven",
    description: "An OTT Platform",
    image: "/Cinemaven.png",
    githubLink: "https://github.com/Algoture/Cinemaven",
    liveLink: "https://cinemavenclient.onrender.com/",
  },
  {
    id: 2,
    title: "KrishiNET",
    description: "Assured Contract Farming Platform",
    image: "/KrishiNET.png",
    githubLink: "",
    liveLink: "https://krishinet.onrender.com/",
  },
  {
    id: 3,
    title: "Shubham Enterprises",
    description: "A web platform for reliable loan services.",
    image: "/SE.png",
    githubLink: "https://github.com/SheshNalwar/Shubham-Enterprises",
    liveLink: "https://shubhamenterprises.onrender.com/",
  },
  {
    id: 4,
    title: "ASG Academy",
    description: "A web platform for kids' skill development.",
    image: "/ASG.png",
    githubLink: "https://github.com/SheshNalwar/ASG-Academy",
    liveLink: "https://asg-academy.onrender.com/",
  },
  {
    id: 5,
    title: "Beat Blend",
    description: "A minimal Designed Music Player",
    image: "/BeatBlend.mp4",
    githubLink: "https://github.com/Algoture/Beat-Blend",
    liveLink: "https://algoture.github.io/Beat-Blend/",
  },
];
export const skills = [
  "Docker",
  "Kubernetes",
  "Next JS",
  "AWS",
  "TypeScript",
  "Golang",
  "React Native",
  "Node JS",
  "Express JS",
  "MongoDB",
  "SQL",
  "Java",
  "Redis",
  "Clerk",
  "GraphQL",
  "PostgreSQL",
  "Kafka",
  "Tauri",
  "Electron",
];
